### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by miguel-negrao** [joseareia/ipleiria-thesis#2]
With the following .latexmkrc this respository does not compile

```
#!/bin/env perl

# PDF-generating modes are:
# 1: pdflatex, as specified by $pdflatex variable (still largely in use)
# 2: postscript conversion, as specified by the $ps2pdf variable (useless)
# 3: dvi conversion, as specified by the $dvipdf variable (useless)
# 4: lualatex, as specified by the $lualatex variable (best)
# 5: xelatex, as specified by the $xelatex variable (second best)
$pdf_mode = 5;

set_tex_cmds("--shell-escape --synctex=1 %O %S");

$root_filename = 'IPleiriaMain.tex';
```

Log attached: [IPleiriaMain.log](https://github.com/user-attachments/files/17659198/IPleiriaMain.log)

**Comment by joseareia** [comment]
Hello, @miguel-negrao!

Thank you for reporting this issue. I'll look into it and aim to resolve it in the next few days.

**Comment by joseareia** [comment]
After some debugging, I discovered that, by mistake, the file located at `Variables/Variables.tex` contained the content of the `IPLeiriaThesis.cls` file. This, as you might expect, was causing the compilation error.

The issue has been resolved, and you should be able to compile the project successfully now. I’ve released an updated version with these changes and added some useful instructions to the project README.

Thanks again for reporting the issue! Let me know if you encounter anything else.

**Comment by miguel-negrao** [comment]
I can confirm it now compiles here also, thanks !
